// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import (
	"context"
)

type Querier interface {
	CreatePost(ctx context.Context, arg CreatePostParams) error
	DeletePostById(ctx context.Context, id int64) error
	GetPostById(ctx context.Context, id int64) (Post, error)
	GetPosts(ctx context.Context) ([]Post, error)
	UpdatePostById(ctx context.Context, arg UpdatePostByIdParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
